CONFIG_ZMK_USB_LOGGING=n

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
CONFIG_BT=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_POINTING=y
CONFIG_SETTINGS=y
CONFIG_BT_SETTINGS=y
CONFIG_SETTINGS_NVS=y
CONFIG_ZMK_SETTINGS_RESET_ON_START=y